language: java
jdk: openjdk8
addons:
  ssh_known_hosts: 129.194.69.128
before_install:
- mkdir /opt/docker-deploy
- cd unihub/docker-config
- cd ..

install: true


script:
- echo "skipping tests"


before_deploy:
- openssl aes-256-cbc -K $encrypted_706caab74578_key -iv $encrypted_706caab74578_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet pom.xml martijs0@129.194.69.128:/opt/docker-deploy/

after_success:
- echo "yeaaah"
- sshpass -p '' scp pom.xml martijs0@129.194.69.128:/opt/docker-deploy/
