language: java
jdk: openjdk8

addons:
  ssh_known_hosts: 129.194.69.128

before_install:
- mkdir /opt/docker-deploy
- cd unihub/docker-config
- "./runDocker.sh"
- cd ..
- find . -type f -iname Cors* -exec sed -i 's/localhost/129.194.69.128/g' {} +

install: true
script: mvn clean install

before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_706caab74578_key -iv $encrypted_706caab74578_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh martijs0@129.194.69.128 rm -f /opt/docker-deploy/* && find /opt/docker-deploy/ -iname "*.war" -exec scp '{}' martijs0@129.194.69.128:/opt/docker-deploy/ ';'
  on:
    branch: master

after_success:
- bash <(curl -s https://codecov.io/bash)

