language: java
jdk: openjdk8
addons:
  ssh_known_hosts:
  - $PRODUCTION_SERVER

before_install:
- echo -e "Host $PRODUCTION_SERVERntStrictHostKeyChecking non" >> ~/.ssh/config
- openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- mkdir /opt/docker-deploy
- cd unihub/docker-config
- "./runDocker.sh"
- cd ..

install: mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
- scp -p22 `find /opt/docker-deploy/ -iname "*.war"` $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER:/opt/docker-deploy/

