language: java
jdk: openjdk8
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir /opt/docker-deploy
  - sudo chmod -R 755 /opt/docker-deploy
  - sudo chmod -R a+x /opt/docker-deploy
  - sudo chown travis:travis /opt/docker-deploy
  - cd unihub/docker-config
  - ./runDocker.sh
  - docker ps
  - uname -a
  - whoami
install:
  - mvn install -DskipTests=true
  - sleep 5
  - ls /opt/docker-deploy/
  - sleep 5
  - ls /opt/docker-deploy/
  - mvn jacoco:prepare-agent clean test
after_success:
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)
