language: java
before_install:
  - mkdir /opt/docker-deploy
  - cd unihub/docker-config
  - ./runDocker.sh
  - cd ..
  - sleep 3
install: mvn jacoco:prepare-agent clean test
after_success:
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)
