CREATE DATABASE UNIHUB_DB;
USE UNIHUB_DB;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME varchar(35),
  PASSWD varchar(1000) NOT NULL,
  EMAIL varchar(255) NOT NULL,
  ROLE varchar(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;