USE UNIHUB_DB;
GRANT ALL PRIVILEGES ON UNIHUB_DB.* TO 'root' WITH GRANT OPTION;
/*INSERT INTO USERS(ID, USERNAME, PASSWD, EMAIL, ROLE) VALUES(1, 'user1','pw1', 'my-email@hotmail.com', 'USER');
INSERT INTO USERS(ID, USERNAME, PASSWD, EMAIL, ROLE) VALUES(2, 'user2','pw2', 'my-email@gmail.com', 'USER');*/
